DataBiosphere/transporter

build.sbt
manager/src/main/resources/reference.conf
manager/src/main/scala/org/broadinstitute/transporter/ManagerConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/db/DbClient.scala
manager/src/main/scala/org/broadinstitute/transporter/db/config/DbConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/db/config/TimeoutConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/AdminClient.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConsumer.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaProducer.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/TimeoutConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/config/ConsumerBatchConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/config/KafkaConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/config/TimeoutConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/config/TopicConfig.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/AdminClientSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/BaseKafkaSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/KafkaConsumerSpec.scala

Step 1 of adding the result processing.

Add Kafka consumer wrapper.

---

.scalafmt.conf
Jenkinsfile
build.sbt
project/plugins.sbt

Mainly bug-fixes, scalafmt bump is the most significant change.

Bump dependencies and add more to CI

---

Jenkinsfile
manager/src/main/scala/org/broadinstitute/transporter/TransporterManager.scala
manager/src/main/scala/org/broadinstitute/transporter/db/DbClient.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConsumer.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaProducer.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/Serdes.scala
manager/src/main/scala/org/broadinstitute/transporter/kafka/config/KafkaConfig.scala
manager/src/main/scala/org/broadinstitute/transporter/queue/QueueController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/RequestStatus.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferStatus.scala
manager/src/main/scala/org/broadinstitute/transporter/web/ApiRoutes.scala
manager/src/main/scala/org/broadinstitute/transporter/web/InfoRoutes.scala
manager/src/main/scala/org/broadinstitute/transporter/web/SwaggerMiddleware.scala
manager/src/main/scala/org/broadinstitute/transporter/web/package.scala
manager/src/test/scala/org/broadinstitute/transporter/PostgresSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/db/DbClientSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/KafkaConsumerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/KafkaProducerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/kafka/SerdesSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/queue/QueueControllerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferControllerSpec.scala

This _should_ be all the manager functionality for the quarter. Working on an integration test to prove it for a later PR.

DSPDC-163 Run request listener in the background, and add query API.

---

agents/echo/README.md
agents/echo/src/main/resources/reference.conf
agents/echo/src/main/scala/org/broadinstitute/transporter/EchoAgent.scala
agents/echo/src/main/scala/org/broadinstitute/transporter/EchoConfig.scala
agents/echo/src/main/scala/org/broadinstitute/transporter/transfer/EchoRunner.scala
agents/template/src/main/resources/logback.xml
agents/template/src/main/resources/reference.conf
agents/template/src/main/scala/org/broadinstitute/transporter/AgentConfig.scala
agents/template/src/main/scala/org/broadinstitute/transporter/TransporterAgent.scala
agents/template/src/main/scala/org/broadinstitute/transporter/kafka/TransferStream.scala
agents/template/src/main/scala/org/broadinstitute/transporter/transfer/TransferRunner.scala
agents/template/src/test/scala/org/broadinstitute/transporter/kafka/TransferStreamSpec.scala
build.sbt
common/src/test/scala/org/broadinstitute/transporter/queue/QueueSchemaSpec.scala
manager/scripts/liquibase-migrate-local
manager/src/main/resources/logback.xml
manager/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConsumer.scala
project/plugins.sbt

In prep for writing the AWS->GCP agent, wanted to do something simpler.

Add echo agent, with tweaks to the template.

---

build.sbt
manager/db-migrations/src/main/resources/changelog.xml
manager/db-migrations/src/main/resources/changesets/04-add-submitted-updated-times.xml
manager/src/main/scala/org/broadinstitute/transporter/db/DbClient.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/RequestStatus.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferStatus.scala
manager/src/main/scala/org/broadinstitute/transporter/web/ApiRoutes.scala
manager/src/test/scala/org/broadinstitute/transporter/db/DbClientSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferControllerSpec.scala

This should help us gauge how long big transfers will take based on smaller trial runs.

DSPDC-274 Track submission & update times for running transfers.

---

agents/aws-to-gcp/src/main/scala/org/broadinstitute/transporter/transfer/AwsToGcpRunner.scala

DSPDC-302 Fix S3 urls for buckets in us-east-1.

---

agents/aws-to-gcp/src/main/scala/org/broadinstitute/transporter/transfer/AwsToGcpRunner.scala

I manually tested this on one of the zero-length V2F files that are currently failing in prod. It should also make transferring small files more efficient in general.

DSPDC-380 Use multipart uploads for small files.

---

agents/aws-to-gcp/src/main/scala/org/broadinstitute/transporter/transfer/AwsToGcpRunner.scala

With some cleanups to transfer control-flow.

DSPDC-382 Use valid content-type values when initializing resumable uploads

---

Jenkinsfile
agents/template/src/main/scala/org/broadinstitute/transporter/kafka/KStreamsConfig.scala
agents/template/src/test/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilderSpec.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConsumer.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/KafkaProducer.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/config/ConnectionConfig.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/config/TlsConfig.scala
common/src/test/scala/org/broadinstitute/transporter/kafka/BaseKafkaSpec.scala

~Will make a follow-up PR for the agent template~
Went ahead and added the agent support here too, since it was easy.

DSPDC-321 Enable using TLS connections in the Transporter manager

---

Jenkinsfile
agents/template/src/main/scala/org/broadinstitute/transporter/kafka/KStreamsConfig.scala
agents/template/src/test/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilderSpec.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/KafkaConsumer.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/KafkaProducer.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/config/ConnectionConfig.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/config/ScramConfig.scala
common/src/main/scala/org/broadinstitute/transporter/kafka/config/TlsConfig.scala
common/src/test/scala/org/broadinstitute/transporter/kafka/BaseKafkaSpec.scala

We use SCRAM for authentication against Kafka.

DSPDC-324 DSPDC-325 Add config for SCRAM

---

.scalafmt.conf
build.sbt
manager/src/test/scala/org/broadinstitute/transporter/info/InfoControllerSpec.scala
project/plugins.sbt

Mostly pulling in bug-fixes, only one source change

Bump most libraries to latest versions.

---

Jenkinsfile
agents/aws-to-gcp/deploy/init-containers/Dockerfile
agents/aws-to-gcp/deploy/init-containers/transporter-aws-to-gcp-agent/application.conf.ctmpl
agents/aws-to-gcp/deploy/init-containers/transporter-aws-to-gcp-agent/entrypoint.sh.ctmpl
build.sbt
manager/deploy/init-containers/openidc-proxy/site.conf
manager/deploy/init-containers/transporter-manager-migrations/entrypoint.sh.ctmpl
manager/deploy/init-containers/transporter-manager/application.conf.ctmpl
manager/deploy/init-containers/transporter-manager/entrypoint.sh.ctmpl
project/TransporterDeployPlugin.scala
project/TransporterDockerPlugin.scala
project/plugins.sbt

move relevant code for deployment init containers next to app code, comingle docker image tagging

Ra dspdc 427 init containers

---

manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/config/TransferSchema.scala
manager/src/main/scala/org/broadinstitute/transporter/web/WebApi.scala

Will comment inline with explanations

Fix wonkiness

---

Jenkinsfile
agents/template/src/main/resources/reference.conf
agents/template/src/main/scala/org/broadinstitute/transporter/AgentConfig.scala
agents/template/src/main/scala/org/broadinstitute/transporter/TransporterAgent.scala
agents/template/src/main/scala/org/broadinstitute/transporter/info/AgentStatus.scala
agents/template/src/main/scala/org/broadinstitute/transporter/info/InfoController.scala
agents/template/src/main/scala/org/broadinstitute/transporter/info/SystemStatus.scala
agents/template/src/main/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilder.scala
agents/template/src/main/scala/org/broadinstitute/transporter/web/WebApi.scala
agents/template/src/main/scala/org/broadinstitute/transporter/web/config/WebConfig.scala
agents/template/src/test/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilderSpec.scala
build.sbt

And fix an NPE in error reporting.

DSPDC-271 Add liveness check to Transporter agent template

---

common/src/main/scala/org/broadinstitute/transporter/transfer/ExpandedTransferIds.scala
common/src/main/scala/org/broadinstitute/transporter/transfer/TransferRequest.scala
common/src/main/scala/org/broadinstitute/transporter/transfer/TransferResult.scala
manager/db-migrations/src/main/resources/changelog.xml
manager/db-migrations/src/main/resources/changesets/15-add-expanded-transfer-status.xml
manager/src/main/scala/org/broadinstitute/transporter/TransporterManager.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferListener.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferStatus.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/api/BulkRequest.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/api/TransferRequest.scala
manager/src/main/scala/org/broadinstitute/transporter/web/WebApi.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferControllerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferListenerSpec.scala
project/build.properties

Add the transfer expansion pieces necessary for operation on the manager side (so primarily updates to the TransferListener and some changes to the TransferController), as well as test updates and one test added. Hit me with that feedback 👊

Ra dspdc 491 expand task

---

Jenkinsfile
agents/aws-to-gcp/src/main/scala/org/broadinstitute/transporter/transfer/AwsToGcpRunner.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/api/TransferDetails.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferControllerSpec.scala
project/build.properties

Will comment explanations inline. No blockers here, so OK to take time in reviewing.

DSPDC-510 Various UKBB fixes

---

manager/src/main/scala/org/broadinstitute/transporter/db/Constants.scala
manager/src/main/scala/org/broadinstitute/transporter/info/InfoController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferController.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferListener.scala
manager/src/main/scala/org/broadinstitute/transporter/transfer/TransferSubmitter.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferControllerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferListenerSpec.scala
manager/src/test/scala/org/broadinstitute/transporter/transfer/TransferSubmitterSpec.scala

TODO: Find the TODO about this, and remove it

DSPDC-521 Capitalize SQL keywords.

---

agents/aws-to-gcp/src/main/scala/org/broadinstitute/transporter/transfer/AwsToGcpRunner.scala
agents/template/src/main/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilder.scala
agents/template/src/main/scala/org/broadinstitute/transporter/transfer/TransferRunner.scala
agents/template/src/test/scala/org/broadinstitute/transporter/kafka/TransferStreamBuilderSpec.scala

update agent template's `step`, update tests, update aws-to-gcp `step`

ra-DSPDC-539-update-agent-step

---

agents/sftp-to-gcs/deploy/init-containers/transporter-sftp-to-gcs-agent/application.conf.ctmpl
agents/sftp-to-gcs/deploy/init-containers/transporter-sftp-to-gcs-agent/entrypoint.sh.ctmpl
agents/sftp-to-gcs/src/main/resources/reference.conf
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/SftpToGcsAgent.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/api/SftpToGcsOutput.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/api/SftpToGcsProgress.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/api/SftpToGcsRequest.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/config/RetryConfig.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/config/RunnerConfig.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/config/TimeoutConfig.scala
agents/sftp-to-gcs/src/main/scala/org/broadinstitute/transporter/transfer/SftpToGcsRunner.scala
agents/sftp-to-gcs/src/test/scala/org/broadinstitute/transporter/transfer/SftpToGcsRunnerSpec.scala
build.sbt

Doesn't handle directories (yet). Will split off a separate ticket for adding that functionality, because it looks like the ANVIL transfer will need it.

DSPDC-509 Add SFTP->GCS agent

---

manager/src/main/scala/org/broadinstitute/transporter/web/WebApi.scala

The new Swagger looks like:
As-is, this PR leaves the main Transporter codebase with references to "request" instead of "batch". I did that to keep the initial diff small, but I can also sweep through and do those renamings.

DSPDC-490 Reorganize manager REST API to be more idiomatic.

---

manager/src/main/scala/org/broadinstitute/transporter/web/WebApi.scala

DSPDC-533 Make route summaries more visible.
